### ISSUE TITLE
.ply file is not ASCII format?

### ISSUE THREAD

**Issue by jagadish482** [bminortx/Android-PLY-Reader#4]
hi , i added my own .ply file to raw folder and i installed app but it showing below error. please help me to solve this.

12-27 17:43:07.882    7409-7424/com.graphics.openglgui E/ReadHeader﹕ File is not ASCII format! Cannot read.
12-27 17:43:07.893    7409-7424/com.graphics.openglgui E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 247
    Process: com.graphics.openglgui, PID: 7409
    java.lang.NullPointerException: Attempt to read from null array
            at com.graphics.openglgui.Mesh.draw(Mesh.java:152)
            at com.graphics.openglgui.GLView$Renderer.onDrawFrame(GLView.java:170)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
12-27 17:43:17.718    7409-7424/? I/Process﹕ Sending signal. PID: 7409 SIG: 9

**Comment by 17100109** [comment]
Were you able to finally add your own .ply file?

**Comment by jagadish482** [comment]
thank you,
My .ply file is BINARY_LITTLE_ENDIAN format ,  3d mesh file and texture information contains in .png file. now how to load this file in my android app. please help me to solve this I am new to this

**Comment by 17100109** [comment]
Same. I have no idea how to load a new ply file. Can you please ask someone to figure it out?
